### ISSUE TITLE
Add automatic style formatting

### ISSUE THREAD

**Issue by russelldj** [open-forest-observatory/automate-metashape#57]
It would be useful to choose a style format and then automatically enforce this. In [geograypher](https://github.com/open-forest-observatory/geograypher) we use `isort` for import ordering and `black` for code formatting. These are managed by github action so it runs automatically on pushes to main and PRs. I think this has worked well and I'd recommend doing the same.

**Comment by youngdjn** [comment]
This would be great! @asidhu0, would you be willing to take this on, given your experience setting this up for Geograypher?
